openapi: 3.2.0
info:
  version: 1.0.10
  title: CareAcademy Organizations API
  description: The CareAcademy API allows integration partners to create seamless flows between their products and CareAcademy systems.
servers:
- url: https://staging.careacademy.com/api/v1
security:
- BasicAuth: []
tags:
- name: Organizations
paths:
  /organizations/{organizationIntegrationId}:
    post:
      summary: Create an organization
      parameters:
      - in: path
        name: organizationIntegrationId
        required: true
        description: The external system's organization ID. For example, if you have multiple agencies in your system, you can provide any unique identifier for your agency.
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
              - organizationName
              - organizationState
              - adminFirstName
              - adminLastName
              - adminEmail
              - adminIntegrationId
              allOf:
              - $ref: '#/components/schemas/OrganizationsRequest'
              properties:
                locationId:
                  type: string
                  description: The ID of the location. If the organization has a single location then a value for locationId is expected to be provided. If an organization is multi location then the locationId value can be omitted, and locations can be added by performing a POST to /locations.
      responses:
        '200':
          description: The CareAcademy organization already exists. The organization was updated with the provided integration ID.
          content:
            '*/*':
              schema:
                type: object
                properties:
                  adminIntegrationId:
                    type: string
                    description: The integration ID for the admin user.
                  signInUrl:
                    type: string
                    description: A temporary url that a browser can be directed to in order to sign in a user to their CareAcademy dashboard.
                  additionalInformation:
                    type: array
                    items:
                      type: string
                      description: 'Additional information about the result of the operation. '
                      enum:
                      - admin created for existing agency
                      - no additional information
        '201':
          description: The organization was successfully created within CareAcademy
          content:
            '*/*':
              schema:
                type: object
                properties:
                  adminIntegrationId:
                    type: string
                    description: The integration ID for the admin user.
                  signInUrl:
                    type: string
                    description: A temporary url that a browser can be directed to in order to sign in a user to their CareAcademy dashboard.
        '202':
          $ref: '#/components/responses/OrganizationsAccepted'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
      tags:
      - Organizations
      operationId: postOrganizationsByOrganizationIntegrationId
      x-operation-id-source: derived
    put:
      summary: Flags an existing organization for review in order to associate the…
      parameters:
      - in: path
        name: organizationIntegrationId
        required: true
        schema:
          type: string
        description: The integration ID for the organization.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              allOf:
              - $ref: '#/components/schemas/OrganizationsRequest'
      responses:
        '202':
          $ref: '#/components/responses/OrganizationsAccepted'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
      tags:
      - Organizations
      operationId: putOrganizationsByOrganizationIntegrationId
      x-operation-id-source: derived
components:
  responses:
    BadRequest:
      description: Bad Request. One or more required parameters are missing or invalid.
      content:
        '*/*':
          schema:
            type: object
            properties:
              additionalInformation:
                description: Information and warnings regarding any problems with the request. For general warnings, the parameterName value will be "_".
                type: array
                items:
                  type: object
                  properties:
                    parameterName:
                      type: string
                    description:
                      type: string
              errors:
                description: An array of field errors. For general errors, the parameterName value will be "_".
                type: array
                items:
                  type: object
                  properties:
                    parameterName:
                      type: string
                    errorDescription:
                      type: string
    UnauthorizedError:
      description: Authentication information is missing or invalid
    OrganizationsAccepted:
      description: The request has been queued for manual processing. This response is issued when the provided information needs to be manually verified by CareAcademy staff because the provided organization and admin information is not sufficient to link an account with an existing CareAcademy organization.
  schemas:
    OrganizationsRequest:
      type: object
      required:
      - organizationName
      - organizationState
      - adminFirstName
      - adminLastName
      - adminEmail
      - adminIntegrationId
      properties:
        organizationName:
          type: string
          description: The organization's name.
        organizationState:
          type: string
          description: The organization's US state or Canadian province. This can be the state/province name or abbreviation.
        adminFirstName:
          type: string
          description: The organization administrator's first name.
        adminLastName:
          type: string
          description: The organization administrator's last name.
        adminEmail:
          type: string
          description: The organization administrator's email address.
        adminPhone:
          type: string
          description: The organization administrator's phone number.
        adminIntegrationId:
          type: string
          description: The organization administrator's integration ID. This is typically the ID of the administrator's record in the system making a call to the CareAcademy API. This ID can be used in subsequent calls to the CareAcademy API.
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
