openapi: 3.2.0
info:
  version: 1.0.10
  title: CareAcademy Locations API
  description: The CareAcademy API allows integration partners to create seamless flows between their products and CareAcademy systems.
servers:
- url: https://staging.careacademy.com/api/v1
security:
- BasicAuth: []
tags:
- name: Locations
paths:
  /locations/{organizationIntegrationId}:
    post:
      summary: Creates an association between an organization and one or more locations.
      parameters:
      - in: path
        name: organizationIntegrationId
        required: true
        schema:
          type: string
        description: The integration ID for the organization. This is the same value passed as the organizationIntegrationId parameter to the Organizations POST API endpoint.
      requestBody:
        content:
          application/json:
            schema:
              anyOf:
              - $ref: '#/components/schemas/Location'
              - $ref: '#/components/schemas/LocationArray'
            examples:
              singleLocation:
                summary: A single location
                value:
                  resourceType: Location
                  id: location-xyz
                  name: Location XYZ
              multipleLocation:
                summary: Multiple locations
                value:
                - resourceType: Location
                  id: location-abc
                  name: Location ABC
                - resourceType: Location
                  id: location-xyz
                  name: Location XYZ
        description: The information required to create a location.
      responses:
        '200':
          $ref: '#/components/responses/LocationCreateOrUpdateSuccess'
        '201':
          $ref: '#/components/responses/LocationCreateOrUpdatePartialSuccess'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '403':
          $ref: '#/components/responses/Forbidden'
      tags:
      - Locations
      operationId: postLocationsByOrganizationIntegrationId
      x-operation-id-source: derived
components:
  responses:
    LocationCreateOrUpdatePartialSuccess:
      description: The operation was partially successful. One or more loations could not be created. See the additionalInformation response property for more information.
      content:
        '*/*':
          schema:
            type: object
            allOf:
            - $ref: '#/components/schemas/LocationCreateOrUpdateResponse'
    UnauthorizedError:
      description: Authentication information is missing or invalid
    Forbidden:
      description: The identity associated with the API credentials for this request is not allowed to perform the requested operation.
    BadRequest:
      description: Bad Request. One or more required parameters are missing or invalid.
      content:
        '*/*':
          schema:
            type: object
            properties:
              additionalInformation:
                description: Information and warnings regarding any problems with the request. For general warnings, the parameterName value will be "_".
                type: array
                items:
                  type: object
                  properties:
                    parameterName:
                      type: string
                    description:
                      type: string
              errors:
                description: An array of field errors. For general errors, the parameterName value will be "_".
                type: array
                items:
                  type: object
                  properties:
                    parameterName:
                      type: string
                    errorDescription:
                      type: string
    LocationCreateOrUpdateSuccess:
      description: The operation was successful.
      content:
        '*/*':
          schema:
            type: object
            allOf:
            - $ref: '#/components/schemas/LocationCreateOrUpdateResponse'
  schemas:
    LocationCreateOrUpdateResponse:
      type: object
      properties:
        additionalInformation:
          description: Information and warnings regarding any problems with the request. For general warnings, the parameterName value will be "_".
          type: array
          items:
            type: object
            properties:
              parameterName:
                type: string
              description:
                type: string
        locations:
          type: array
          items:
            type: object
            allOf:
            - $ref: '#/components/schemas/Location'
    Location:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        resourceType:
          type: string
          enum:
          - Location
    LocationArray:
      properties:
        locations:
          type: array
          items:
            type: object
            allOf:
            - $ref: '#/components/schemas/Location'
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
