openapi: 3.2.0
info:
  version: 1.0.10
  title: CareAcademy Sign In Url API
  description: The CareAcademy API allows integration partners to create seamless flows between their products and CareAcademy systems.
servers:
- url: https://staging.careacademy.com/api/v1
security:
- BasicAuth: []
tags:
- name: Sign In Url
paths:
  /sign_in_url:
    get:
      summary: Retrieve a sign in url for a given user for Single Sign On.
      parameters:
      - in: query
        name: userIntegrationId
        description: The external system's user ID. This is typically the ID of the user's record in the system making a call to the CareAcademy API.
        schema:
          type: string
      - in: query
        name: email
        description: The email address of the user being signed in.
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: object
                properties:
                  signInUrl:
                    type: string
                    description: A temporary url that a browser can be directed to in order to sign in a user to their CareAcademy dashboard.
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '403':
          description: Forbidden. The requested user is not allowed to sign in through SSO.
        '404':
          description: User not found.
      tags:
      - Sign In Url
      operationId: getSignInUrl
      x-operation-id-source: derived
components:
  responses:
    BadRequest:
      description: Bad Request. One or more required parameters are missing or invalid.
      content:
        '*/*':
          schema:
            type: object
            properties:
              additionalInformation:
                description: Information and warnings regarding any problems with the request. For general warnings, the parameterName value will be "_".
                type: array
                items:
                  type: object
                  properties:
                    parameterName:
                      type: string
                    description:
                      type: string
              errors:
                description: An array of field errors. For general errors, the parameterName value will be "_".
                type: array
                items:
                  type: object
                  properties:
                    parameterName:
                      type: string
                    errorDescription:
                      type: string
    UnauthorizedError:
      description: Authentication information is missing or invalid
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
